<%@ Page Title="" Language="C#" MasterPageFile="~/admin/admin.master" AutoEventWireup="true" CodeFile="Addcategory.aspx.cs" Inherits="admin_admin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
    .style12
    {
        width: 145px;
    }
    .style14
    {
        width: 232px;
    }
    .style17
    {
        height: 21px;
    }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="style1" style="height: 256px; width: 100%">
    <tr>
        <td colspan="2" class="tblhead">
            Add Category</td>
    </tr>
    <tr>
        <td class="style12">
            &nbsp;</td>
        <td class="style14">
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style12">
            &nbsp;</td>
        <td class="style14">
            &nbsp;</td>
    </tr>
    <tr>
        <td class="lbl">
            Category Name:</td>
        <td style="text-align: left">
            <asp:TextBox ID="txtname" runat="server" placeholder="Enter Category Name!!!" 
                CssClass="txt" Width="141px" ValidationGroup="qwer1" ></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                ControlToValidate="txtname" ErrorMessage="Enter Category" 
                ForeColor="#CC0000" ValidationGroup="qwer1"></asp:RequiredFieldValidator>
        </td>
    </tr>
    <tr>
        <td class="style17">
            </td>
        <td style="text-align: left" class="style17">
            <asp:Button ID="btnadd" runat="server" BorderColor="#FFFF99" CssClass="btn" 
                style="margin-left: 0px" Text="ADD" Width="70px" onclick="btnadd_Click" 
                Height="30px" ValidationGroup="qwer1" />
        </td>
    </tr>
    <tr>
        <td class="style17">
            &nbsp;</td>
        <td style="text-align: left" class="style17">
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style12">
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                DeleteCommand="DELETE FROM [category] WHERE [Cid] = @Cid" 
                InsertCommand="INSERT INTO [category] ([Cid], [Cname]) VALUES (@Cid, @Cname)" 
                SelectCommand="SELECT * FROM [category]" 
                UpdateCommand="UPDATE [category] SET [Cname] = @Cname WHERE [Cid] = @Cid">
                <DeleteParameters>
                    <asp:Parameter Name="Cid" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Cid" Type="String" />
                    <asp:Parameter Name="Cname" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Cname" Type="String" />
                    <asp:Parameter Name="Cid" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </td>
        <td class="style14">
            <asp:GridView ID="GridView1" runat="server"
                onrowcancelingedit="GridView1_RowCancelingEdit1" 
                onrowdeleting="GridView1_RowDeleting1" onrowediting="GridView1_RowEditing1" 
                onrowupdating="GridView1_RowUpdating1" 
                onselectedindexchanged="GridView1_SelectedIndexChanged" CellPadding="4" GridLines="None" 
                Width="343px" style="text-align: center" EmptyDataText="No Data" 
                ForeColor="#333333" AutoGenerateColumns="False" 
                AutoGenerateDeleteButton="True" DataKeyNames="Cid" 
                DataSourceID="SqlDataSource1">
                
                <AlternatingRowStyle BackColor="White" />
                
                <Columns>
                    <asp:BoundField DataField="Cid" HeaderText="Cid" ReadOnly="True" 
                        SortExpression="Cid" />
                    <asp:BoundField DataField="Cname" HeaderText="Cname" SortExpression="Cname" />
                </Columns>
                
                <FooterStyle BackColor="#990000" ForeColor="White" Font-Bold="True" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                <SortedAscendingCellStyle BackColor="#FDF5AC" />
                <SortedAscendingHeaderStyle BackColor="#4D0000" />
                <SortedDescendingCellStyle BackColor="#FCF6C0" />
                <SortedDescendingHeaderStyle BackColor="#820000" />
            </asp:GridView>
        </td>
    </tr>
</table>
</asp:Content>

